const arr = [
  {
    params: ["username"],
    url: "https://twitter.com/${username}",
    srcDoc: "<a class='twitter-timeline' href='https://twitter.com/${username}?ref_src=twsrc%5Etfw'>Tweets by ${username}</a><script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>",
    id: "twitter_profile",
    name: "Twitter Profile",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["username", "tweetId"],
    url: "https://twitter.com/${username}/status/${tweetId}",
    srcDoc: "<blockquote class='twitter-tweet'>&amp;mdash; ${username} <a href='https://twitter.com/${username}/status/${tweetId}?ref_src=twsrc%5Etfw'>(@${username})</a></blockquote><script async src='https://platform.twitter.com/widgets.js' charset='utf-8'></script>",
    id: "twitter_tweet",
    name: "Twitter",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["username"],
    url: "https://www.tiktok.com/@${username}",
    srcDoc: "<blockquote class='tiktok-embed' cite='https://www.tiktok.com/${username}' data-unique-id='${username}'  data-embed-type='creator' style='max-width: 750px; min-width: 250px;'<section> <a target='_blank' href='https://www.tiktok.com/@${username}?refer=creator_embed'>@${username}</a> </section></blockquote> <script async src='https://www.tiktok.com/embed.js'></script>",
    id: "tiktok_profile",
    name: "Tiktok Profile",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["username", "videoId"],
    url: "https://www.tiktok.com/@${username}/video/${videoId}",
    srcDoc: "<blockquote class='tiktok-embed' cite='https://www.tiktok.com/@${username}/video/${videoId}' data-video-id='${videoId}' style='max-width: 605px;min-width: 250px;'><section> <a target='_blank' title='@${username}' href='https://www.tiktok.com/@${username}'>@${username}</a></section></blockquote><script async src='https://www.tiktok.com/embed.js'></script>",
    id: "tiktok_video",
    name: "Tiktok",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["username", "width", "height"],
    url: "https://www.pinterest.com/${username}",
    srcDoc: "<a data-pin-do='embedUser' data-pin-board-width='${width}' data-pin-scale-height='${height}' data-pin-scale-width='80' href='https://www.pinterest.com/${username}/'></a><script async defer src='//assets.pinterest.com/js/pinit.js'></script>",
    id: "pinterest",
    name: "pinterest",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["videoId", "h", "app_id"],
    url: "https://player.vimeo.com/video/${videoId}?h=${h} app_id=${app_id}",
    id: "vimeo",
    name: "vimeo",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["videoId"],
    url: "https://www.youtube.com/embed/${videoId}",
    id: "youtube",
    name: "youtube",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["musicId"],
    url: "https://open.spotify.com/embed/track/${musicId}?utm_source=generator",
    id: "spotify",
    name: "Spotify Music",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["channelId"],
    url: "https://player.twitch.tv/?channel=${channelId}&parent=nffriend.com&referrer=about:srcdoc",
    id: "twitch",
    name: "twitch",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["projectId", "projectName"],
    cookie: true,
    url: "https://www.kickstarer.com/projects/${projectId}/${projectName}/widget/video.html",
    id: "kickstarer",
    name: "kickstarer",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: [],
    cookie: true,
    url: "https://app.uniswap.org/",
    id: "uniswap",
    name: "Uniswap",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["chainName", "address", "tokenId"],
    url: "https://opensea.io/assets/${chainName}/${address}/${tokenId}",
    srcDoc: "<nft-card contractAddress='${address}' tokenId='${tokenId}'></nft-card><script src='https://unpkg.com/embeddable-nfts/dist/nft-card.min.js'></script>",
    id: "opensea",
    name: "Opensea",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["feedId"],
    url: "https://rss3.app/feed/${feedId}",
    srcDoc: "<rssapp-list id='${feedId}'></rssapp-list><script src='https://widget.rss.app/v1/list.js' type='text/javascript' async></script>",
    id: "rss3",
    name: "Rss3",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["roomId", "wallet"],
    url: "https://sky001-1300260371.cos.ap-hongkong.myqcloud.com/game/index.html?roomId=${roomId}&wallet=${wallet}",
    id: "sky001",
    name: "Sky001",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["worldId"],
    url: "https://www.nftworlds.com/${worldId}",
    id: "nftworlds",
    name: "Nftworlds",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: [],
    url: "https://raritysniper.com/nft-drops-calendar",
    css: "border: 'none'; width: '1520px'; height: '600px'; position: 'absolute'; left: '-300px'; top: '-250px', bottom: '-180px';",
    id: "raritysniper",
    name: "Raritysniper",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["username"],
    url: "https://shil.me/${username}",
    css: "border: 'none'; width: '1400px'; height: '800px'; position: 'absolute'; left: '-100px'; top: '-400px';",
    id: "shil",
    name: "Shil",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: ["coords"],
    url: "https://voxels.com/play?coords=${coords}",
    id: "voxels",
    name: "Voxels",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: [],
    url: "https://coinmarketcap.com/zh/widget/price-marquee/",
    srcDoc: "<script type='text/javascript' src='https://files.coinmarketcap.com/static/widget/coinMarquee.js'></script><div id='coinmarketcap-widget-marquee' coins='1,1027,1839,4195,3897' currency='USD' theme='light' transparent='false' show-symbol-logo='true'></div>",
    id: "CMC_marquee",
    name: "Coin Market Cap",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: [],
    url: "https://www.cryptohopper.com/website-widgets",
    srcDoc: "<div class='cryptohopper-web-widget' data-id='5' data-news_count='5'></div><script src='https://www.cryptohopper.com/widgets/js/script'></script>",
    id: "CH_news",
    name: "Cryptohopper",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: [],
    url: "https://www.coingecko.com/en/widgets/coin_heatmap_widget",
    srcDoc: "<script src='https://widgets.coingecko.com/coingecko-coin-heatmap-widget.js'></script><coingecko-coin-heatmap-widget  height='500' locale='en'></coingecko-coin-heatmap-widget>",
    id: "CG_heatmap",
    name: "Coingecko",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
  {
    params: [],
    url: "https://cryptorank.io/widgets/ieo-roi",
    srcDoc: "<div class='cr-widget' data-api-url: https://api.cryptorank.io data-site-url: https://cryptorank.io data-currency='USD' data-type='all' data-roi='both' data-sort='ROI' style='width: 100%; height: 750px;'><a target='_blank' rel='noopener' href='https://cryptorank.io/ieo-platforms-roi'>IEO Returns by Cryptorank</a></div><script src='https://cryptorank.io/widget/ieo-roi.js'></script>",
    id: "CR_chart",
    name: "Cryptorank",
    star: "",
    info: "简介简介简介简介简介简介简介简介简介简介",
    icon: "/static/nff/icon-twitter.png",
  },
];

export default arr;
